name: Publish Python 🐍 distributions 📦 to PyPI
on:
    push:
        branches:
            - main
        paths:
            - "gcc_play/**"
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - main
permissions:
    contents: read
jobs:
    publish-and-create-releases:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10"]
                poetry-version: ["1.2.0b3"]
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install poetry
              uses: abatilo/actions-poetry@v2.1.3
              with:
                  poetry-version: ${{ matrix.poetry-version }}

            - name: PyPI setting
              run: |
                  poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

            - name: build gcc_play
              run: |
                  poetry build

            - name: Publish distribution 📦 to PyPI
              if: github.event_name == 'push'
              run: |
                  poetry publish
